on: push
name: Main
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: actions/npm@master
      with:
        args: ci
    - name: Jest
      uses: docker://node
      with:
        args: ./node_modules/.bin/jest
    - name: Lint
      uses: docker://node
      with:
        args: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
    - name: TypeScript
      uses: docker://node
      with:
        args: ./node_modules/.bin/tsc --build
    - name: Master
      uses: actions/bin/filter@master
      with:
        args: branch master
    - name: Publish
      uses: docker://node
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: script/publish --yes from-git
