on: push
name: Validate
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/npm@master
      with:
        args: ci
    - uses: docker://node
      with:
        args: ./node_modules/.bin/jest
    - uses: docker://node
      with:
        args: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
    - uses: docker://node
      with:
        args: ./node_modules/.bin/tsc --build
    - if: github.ref == 'refs/heads/master'
      uses: docker://node
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: script/publish --yes from-git
