on: push
name: Validate
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"
    - run: npm install
    - run: ./node_modules/.bin/jest
    - run: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
    - run: ./node_modules/.bin/tsc --build
    - if: github.ref == 'refs/heads/master'
      run: script/publish --yes from-git
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
